### ISSUE TITLE
'}' in server.js

### ISSUE THREAD

**Issue by Shimork04** [Calatop/Zenitsu-bot#1]
Syntax error : extra bracket **'}**' in 'client.on' function 

![image](https://github.com/rohzzn/zenitsu-bot/assets/111634234/985a2f5e-f854-402d-ac4e-381a5667a1fc)

**Comment by rohzzn** [comment]
fixed it, thank you!
<img width="434" alt="image" src="https://github.com/rohzzn/zenitsu-bot/assets/47408756/ccb95ce7-978e-4ef6-95f9-f15d9ee9d430">
